<a href="https://colab.research.google.com/github/albertosire/keras-cifar10-test/blob/main/keras_cifar10_atividade_previa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from __future__ import print_function
from PIL import Image
import requests
from io import BytesIO

import numpy as np

from keras.callbacks import EarlyStopping
from keras.datasets import cifar10
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Flatten
from keras.layers.convolutional import Conv2D
from keras.optimizers import Adam
from keras.layers.pooling import MaxPooling2D
from keras.utils import to_categorical


In [2]:
np.random.seed(1000)

(X_train, Y_train), (X_test, Y_test) = cifar10.load_data()

# Create the model
model = Sequential()

model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(32, 32, 3)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(1024, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))


170500096/170498071 [==============================] - 4s 0us/step


In [3]:
model.compile(loss='categorical_crossentropy',
              optimizer=Adam(lr=0.0001, decay=1e-6),
              metrics=['accuracy'])

model.fit(X_train / 255.0, to_categorical(Y_train),
          batch_size=128,
          shuffle=True,
          epochs=10,
          validation_data=(X_test / 255.0, to_categorical(Y_test)))

scores = model.evaluate(X_test / 255.0, to_categorical(Y_test))

print('Loss: %.3f' % scores[0])
print('Accuracy: %.3f' % scores[1])


Epoch 1/10
391/391 [==============================] - 2s 6ms/step - loss: 1.8955 - accuracy: 0.3161 - val_loss: 1.6024 - val_accuracy: 0.4348
Epoch 2/10
391/391 [==============================] - 2s 5ms/step - loss: 1.5292 - accuracy: 0.4544 - val_loss: 1.4060 - val_accuracy: 0.5099
Epoch 3/10
391/391 [==============================] - 2s 5ms/step - loss: 1.4015 - accuracy: 0.5008 - val_loss: 1.3255 - val_accuracy: 0.5340
Epoch 4/10
391/391 [==============================] - 2s 5ms/step - loss: 1.3324 - accuracy: 0.5283 - val_loss: 1.2631 - val_accuracy: 0.5566
Epoch 5/10
391/391 [==============================] - 2s 5ms/step - loss: 1.2823 - accuracy: 0.5487 - val_loss: 1.2252 - val_accuracy: 0.5751
Epoch 6/10
391/391 [==============================] - 2s 5ms/step - loss: 1.2364 - accuracy: 0.5638 - val_loss: 1.1850 - val_accuracy: 0.5882
Epoch 7/10
391/391 [==============================] - 2s 5ms/step - loss: 1.2034 - accuracy: 0.5765 - val_loss: 1.1553 - val_accuracy: 0.5945
Epoch 

In [19]:

response = requests.get('https://dl1.cbsistatic.com/i/r/2017/02/01/4094f803-44d1-47e0-a22f-6d48f65727b5/thumbnail/32x32/4188676421c43926bfcb5f3329ffacb6/fmimg586302198861076950.png')
img = Image.open(BytesIO(response.content))
img = np.expand_dims(img, axis=0)
img = img[:,:,:,:3]

print(model.predict(img))


[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
import cv2

In [15]:
response = requests.get('https://miro.medium.com/max/700/0*kp8rJzqHjagMj22J')

img = Image.open(BytesIO(response.content))

img = img.resize((32, 32), Image.ANTIALIAS)

img = np.expand_dims(img, axis=0)
img = img[:,:,:,:3]

print(model.predict(img))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [18]:
response = requests.get('https://ichef.bbci.co.uk/news/1024/cpsprodpb/83D7/production/_111515733_gettyimages-1208779325.jpg') #cat

img = Image.open(BytesIO(response.content))

img = img.resize((32, 32), Image.ANTIALIAS)

img = np.expand_dims(img, axis=0)
img = img[:,:,:,:3]

print(model.predict(img))

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


In [76]:
testes = ["https://dl1.cbsistatic.com/i/r/2017/02/01/4094f803-44d1-47e0-a22f-6d48f65727b5/thumbnail/32x32/4188676421c43926bfcb5f3329ffacb6/fmimg586302198861076950.png"] #plane
testes.append("https://miro.medium.com/max/700/0*kp8rJzqHjagMj22J") #plane
testes.append("https://ichef.bbci.co.uk/news/1024/cpsprodpb/83D7/production/_111515733_gettyimages-1208779325.jpg") #cat
testes.append("https://www.albugle.com/wp-content/uploads/2019/02/cat.jpg") #cat
testes.append("https://d17fnq9dkz9hgj.cloudfront.net/uploads/2012/11/guidelines-for-placing-your-bird-thinkstock-93216977.jpg") #bird
testes.append("https://static.timesofisrael.com/www/uploads/2013/04/%D7%93%D7%A8%D7%A8%D7%94-%D7%A6%D7%99%D7%9C%D7%95%D7%9D-%D7%93%D7%95%D7%A8%D7%95%D7%9F-%D7%94%D7%95%D7%A4%D7%9E%D7%9F-1-640x400.jpg") #bird
testes.append("https://scx1.b-cdn.net/csz/news/800/2019/uscresearche.jpg") #bird
testes.append("https://static01.nyt.com/images/2019/06/17/science/17DOGS/17DOGS-superJumbo.jpg?quality=90&auto=webp") #dog
testes.append("https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/20113314/Carolina-Dog-standing-outdoors.jpg") #dog
testes.append("https://i.insider.com/5484b33a6da8119577fbada9?width=700&format=jpeg&auto=webp") #dog
testes.append("https://www.marineinsight.com/wp-content/uploads/2015/03/norwegian-cruise.jpg") #ship
testes.append("https://specials-images.forbesimg.com/imageserve/5e8a2071e2bb040006427fae/960x0.jpg?fit=scale") #ship
testes.append("https://drivetribe.imgix.net/Qjw4y3suTUe5iKhTpA6ulA?w=800&h=450&fm=webp&auto=compress&lossless=true&fit=crop&crop=faces&dpr=1") #car

#Expected 1,1,4,4,3,3,3,6,6,6,9,9,2
#[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
#[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
#[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
#[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
#[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
#[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
#[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
#[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
#[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
#[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
#[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
#[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
#[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
result = []
for url in testes:
  response = requests.get(url)
  img = Image.open(BytesIO(response.content))
  img = img.resize((32, 32), Image.ANTIALIAS)
  img = np.expand_dims(img, axis=0)
  img = img[:,:,:,:3]
  print(model.predict(img))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
